# Base configuration
[build]
	ignore    = "git diff --quiet HEAD^ HEAD ."
	command   = "npm run prod"
	functions = "publish_functions"
	publish   = "out"
[build.environment]
	SANITY_STUDIO_API_PROJECT_ID = "twyxjddm"
	DEPLOY_ENV                   = "development"
	SANITY_STUDIO_API_DATASET    = "stage"
	PREVIEW                      = "true"
	DATAINTERFACE_TYPE			 = "sanity"
	IMAGE_PROVIDERS				 = "cloudinary,sanity,local,lorempicsum"
	CLOUDINARY_CLOUDNAME		 = "ded6cg5ry"
	URL                       	 = "https://dev--stink-boilerplate.netlify.app/"

# Production branch
[context.production]
	command = "echo 'Production'; DEPLOY_ENV=production npm run prod"

[context.production.environment]
	URL                       = "https://example.com"
	SANITY_STUDIO_API_DATASET = "production"
	DEPLOY_ENV                = "production"
	PREVIEW                   = "false"
	NEXT_PUBLIC_GA_ID         = "UA-149378133-1"

# Production branch
[context.stage]
	command = "echo 'Production'; DEPLOY_ENV=stage npm run build"

# Preview branch
[context.stage.environment]
	DEPLOY_ENV                = "stage"
	URL                       = "https://stage--stink-boilerplate.netlify.app/"

# QA branch
[context.cms]
	command = "echo 'QA'; DEPLOY_ENV=cms npm run build"
	
[context.cms.environment]
	DEPLOY_ENV                = "cms"
	PREVIEW                   = "false"
	URL                       = "https://cms--stink-boilerplate.netlify.app/"

# QA branch
[context.qa]
	command = "echo 'QA'; DEPLOY_ENV=qa npm run prod"
[context.qa.environment]
	DEPLOY_ENV                = "qa"
	PREVIEW                   = "false"
	URL                       = "https://qa--stink-boilerplate.netlify.app/"


[[plugins]]
	package = "@netlify/plugin-nextjs"

[[redirects]]
	from = "/*"
	to = "/404.html"
	status = 404
